// partLibraryData.js — H-eduware electronics part library
// ES module; no external dependencies.

export const PART_CATEGORIES = [
  { id: 'boards',       label: 'Microcontroller Boards' },
  { id: 'displays',     label: 'Displays' },
  { id: 'sensors',      label: 'Sensors' },
  { id: 'actuators',    label: 'Actuators' },
  { id: 'ics',          label: 'ICs & Drivers' },
  { id: 'passives',     label: 'Passive Components' },
  { id: 'inputs',       label: 'Input Devices' },
  { id: 'power-comms',  label: 'Power & Communication' },
  { id: 'prototyping',  label: 'Prototyping' },
];

export const PART_LIBRARY = [

  // ── BOARDS ───────────────────────────────────────────────────────────────
  {
    id: 'arduino-uno-r3',
    name: 'Arduino Uno R3',
    category: 'boards',
    description: 'The most popular beginner microcontroller board based on the ATmega328P.',
    pins: [
      { name: '5V',   role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'D13',  role: 'digital' },
      { name: 'A0',   role: 'analog'  },
      { name: 'D0',   role: 'rx'      },
      { name: 'D1',   role: 'tx'      },
    ],
    model: {
      kind: 'board',
      size: [2.0, 0.12, 1.7],
      colors: { body: '#0a765d', accent: '#ff7759', detail: '#c8a200' },
    },
  },
  {
    id: 'arduino-nano',
    name: 'Arduino Nano',
    category: 'boards',
    description: 'Compact breadboard-friendly ATmega328P board with mini-USB connector.',
    pins: [
      { name: '5V',   role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'D12',  role: 'digital' },
      { name: 'A3',   role: 'analog'  },
      { name: 'TX',   role: 'tx'      },
      { name: 'RX',   role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [1.1, 0.1, 0.55],
      colors: { body: '#0a765d', accent: '#c8a200', detail: '#1a1a2e' },
    },
  },
  {
    id: 'arduino-mega2560',
    name: 'Arduino Mega 2560',
    category: 'boards',
    description: 'Large ATmega2560 board with 54 digital I/O pins, ideal for complex projects.',
    pins: [
      { name: '5V',   role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'D2',   role: 'pwm'     },
      { name: 'A0',   role: 'analog'  },
      { name: 'TX0',  role: 'tx'      },
      { name: 'RX0',  role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [2.5, 0.12, 1.7],
      colors: { body: '#0a765d', accent: '#c8a200', detail: '#222244' },
    },
  },
  {
    id: 'arduino-leonardo',
    name: 'Arduino Leonardo',
    category: 'boards',
    description: 'ATmega32u4 board that appears as a USB keyboard or mouse to your computer.',
    pins: [
      { name: '5V',  role: 'power'   },
      { name: 'GND', role: 'ground'  },
      { name: 'D9',  role: 'pwm'     },
      { name: 'A1',  role: 'analog'  },
      { name: 'SDA', role: 'data'    },
      { name: 'SCL', role: 'clock'   },
    ],
    model: {
      kind: 'board',
      size: [2.0, 0.12, 1.4],
      colors: { body: '#0a5f7d', accent: '#ff7759', detail: '#c8a200' },
    },
  },
  {
    id: 'arduino-pro-mini',
    name: 'Arduino Pro Mini',
    category: 'boards',
    description: 'Minimal ATmega328P board without USB chip, great for size-constrained builds.',
    pins: [
      { name: 'VCC', role: 'power'   },
      { name: 'GND', role: 'ground'  },
      { name: 'D3',  role: 'pwm'     },
      { name: 'A0',  role: 'analog'  },
      { name: 'TX',  role: 'tx'      },
      { name: 'RX',  role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [0.9, 0.1, 0.5],
      colors: { body: '#c2362f', accent: '#ffcc00', detail: '#1a1a2e' },
    },
  },
  {
    id: 'arduino-micro',
    name: 'Arduino Micro',
    category: 'boards',
    description: 'Tiny ATmega32u4 board with native USB HID support on a compact form factor.',
    pins: [
      { name: '5V',  role: 'power'   },
      { name: 'GND', role: 'ground'  },
      { name: 'D5',  role: 'pwm'     },
      { name: 'A0',  role: 'analog'  },
      { name: 'TX',  role: 'tx'      },
      { name: 'RX',  role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [0.85, 0.1, 0.45],
      colors: { body: '#0a765d', accent: '#c8a200', detail: '#ffffff' },
    },
  },
  {
    id: 'esp32-devkit',
    name: 'ESP32 DevKit V1',
    category: 'boards',
    description: 'Dual-core WiFi and Bluetooth SoC board with 34 GPIO pins for IoT projects.',
    pins: [
      { name: '3V3',  role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'GPIO2',role: 'digital' },
      { name: 'GPIO34',role:'analog'  },
      { name: 'TX',   role: 'tx'      },
      { name: 'RX',   role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [1.3, 0.1, 0.7],
      colors: { body: '#1f3a5f', accent: '#ff7759', detail: '#aaaaaa' },
    },
  },
  {
    id: 'esp8266-nodemcu',
    name: 'NodeMCU ESP8266',
    category: 'boards',
    description: 'Low-cost WiFi board based on ESP8266 with Lua scripting and Arduino support.',
    pins: [
      { name: '3V3',  role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'D1',   role: 'digital' },
      { name: 'A0',   role: 'analog'  },
      { name: 'TX',   role: 'tx'      },
      { name: 'RX',   role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [1.2, 0.1, 0.65],
      colors: { body: '#1a5276', accent: '#e8c200', detail: '#aaaaaa' },
    },
  },
  {
    id: 'raspberry-pi-pico',
    name: 'Raspberry Pi Pico',
    category: 'boards',
    description: 'RP2040 dual-core ARM Cortex-M0+ microcontroller with 26 GPIO and USB.',
    pins: [
      { name: '3V3',  role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'GP2',  role: 'digital' },
      { name: 'GP26', role: 'analog'  },
      { name: 'GP0',  role: 'tx'      },
      { name: 'GP1',  role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [1.3, 0.1, 0.55],
      colors: { body: '#006933', accent: '#ffcc00', detail: '#c0c0c0' },
    },
  },
  {
    id: 'stm32-bluepill',
    name: 'STM32 Blue Pill',
    category: 'boards',
    description: 'Affordable STM32F103C8T6 ARM Cortex-M3 board popular for advanced projects.',
    pins: [
      { name: '3V3',  role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'PA0',  role: 'analog'  },
      { name: 'PB6',  role: 'data'    },
      { name: 'PA9',  role: 'tx'      },
      { name: 'PA10', role: 'rx'      },
    ],
    model: {
      kind: 'board',
      size: [1.1, 0.1, 0.55],
      colors: { body: '#1f6fb2', accent: '#ffffff', detail: '#333388' },
    },
  },
  {
    id: 'attiny85-board',
    name: 'ATtiny85 Digispark',
    category: 'boards',
    description: 'Tiny USB-enabled ATtiny85 board that fits directly into a USB port.',
    pins: [
      { name: 'VCC', role: 'power'   },
      { name: 'GND', role: 'ground'  },
      { name: 'P0',  role: 'digital' },
      { name: 'P2',  role: 'digital' },
      { name: 'P3',  role: 'data'    },
      { name: 'P4',  role: 'clock'   },
    ],
    model: {
      kind: 'board',
      size: [0.7, 0.1, 0.45],
      colors: { body: '#222244', accent: '#ff7759', detail: '#555577' },
    },
  },
  {
    id: 'teensy40',
    name: 'Teensy 4.0',
    category: 'boards',
    description: '600 MHz ARM Cortex-M7 USB development board with exceptional processing power.',
    pins: [
      { name: '3V3',  role: 'power'   },
      { name: 'GND',  role: 'ground'  },
      { name: 'D0',   role: 'rx'      },
      { name: 'D1',   role: 'tx'      },
      { name: 'A0',   role: 'analog'  },
      { name: 'D6',   role: 'pwm'     },
    ],
    model: {
      kind: 'board',
      size: [0.9, 0.1, 0.5],
      colors: { body: '#c2362f', accent: '#ffffff', detail: '#ffcc00' },
    },
  },

  // ── DISPLAYS ─────────────────────────────────────────────────────────────
  {
    id: 'oled-096-i2c',
    name: 'OLED 0.96" I2C',
    category: 'displays',
    description: '128x64 monochrome OLED display communicating over I2C, great for small readouts.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
    ],
    model: {
      kind: 'display',
      size: [0.7, 0.08, 0.55],
      colors: { body: '#17171c', accent: '#0066ff', detail: '#333333' },
    },
  },
  {
    id: 'oled-13-i2c',
    name: 'OLED 1.3" I2C',
    category: 'displays',
    description: '128x64 OLED display in a larger 1.3-inch screen for easier reading.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
    ],
    model: {
      kind: 'display',
      size: [0.9, 0.08, 0.7],
      colors: { body: '#17171c', accent: '#00aaff', detail: '#333333' },
    },
  },
  {
    id: 'lcd-16x2',
    name: '16x2 LCD Display',
    category: 'displays',
    description: 'Classic 16-column by 2-row character LCD with blue backlight and I2C adapter.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SDA', role: 'data'   },
      { name: 'SCL', role: 'clock'  },
    ],
    model: {
      kind: 'display',
      size: [1.6, 0.1, 0.7],
      colors: { body: '#004488', accent: '#00ccff', detail: '#003366' },
    },
  },
  {
    id: 'lcd-20x4',
    name: '20x4 LCD Display',
    category: 'displays',
    description: 'Large 20x4 character LCD that shows four lines of twenty characters with backlight.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SDA', role: 'data'   },
      { name: 'SCL', role: 'clock'  },
    ],
    model: {
      kind: 'display',
      size: [2.2, 0.1, 0.85],
      colors: { body: '#004488', accent: '#00ffcc', detail: '#003366' },
    },
  },
  {
    id: 'tft-18',
    name: 'TFT LCD 1.8" SPI',
    category: 'displays',
    description: 'Full-color 128x160 TFT display using SPI, can show images and colorful graphics.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCK', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
      { name: 'CS',  role: 'enable' },
      { name: 'RS',  role: 'signal' },
    ],
    model: {
      kind: 'display',
      size: [1.1, 0.1, 0.85],
      colors: { body: '#c2362f', accent: '#ff9900', detail: '#333333' },
    },
  },
  {
    id: '7seg-1digit',
    name: '7-Segment 1-Digit',
    category: 'displays',
    description: 'Single red digit seven-segment LED display for numeric readouts.',
    pins: [
      { name: 'A',   role: 'signal' },
      { name: 'B',   role: 'signal' },
      { name: 'GND', role: 'ground' },
      { name: 'DP',  role: 'signal' },
    ],
    model: {
      kind: 'display',
      size: [0.5, 0.09, 0.7],
      colors: { body: '#17171c', accent: '#ff2200', detail: '#333333' },
    },
  },
  {
    id: '7seg-4digit-tm1637',
    name: '4-Digit 7-Seg TM1637',
    category: 'displays',
    description: 'Four-digit seven-segment display driven by TM1637 over two-wire interface.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'CLK', role: 'clock'  },
      { name: 'DIO', role: 'data'   },
    ],
    model: {
      kind: 'display',
      size: [1.4, 0.09, 0.55],
      colors: { body: '#17171c', accent: '#ff2200', detail: '#444444' },
    },
  },
  {
    id: '8x8-matrix-max7219',
    name: '8x8 LED Matrix MAX7219',
    category: 'displays',
    description: 'Eight-by-eight red LED dot-matrix display driven by the MAX7219 SPI controller.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'CLK', role: 'clock'  },
      { name: 'CS',  role: 'enable' },
      { name: 'DIN', role: 'data'   },
    ],
    model: {
      kind: 'display',
      size: [0.9, 0.1, 0.9],
      colors: { body: '#17171c', accent: '#ff2200', detail: '#222222' },
    },
  },
  {
    id: 'nokia-5110',
    name: 'Nokia 5110 LCD',
    category: 'displays',
    description: '84x48 pixel monochrome LCD from the Nokia 5110 phone, uses PCD8544 controller.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'CLK', role: 'clock'  },
      { name: 'DIN', role: 'data'   },
      { name: 'CE',  role: 'enable' },
      { name: 'DC',  role: 'signal' },
    ],
    model: {
      kind: 'display',
      size: [1.1, 0.08, 0.7],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'epaper-213',
    name: 'E-Paper 2.13" HAT',
    category: 'displays',
    description: 'Low-power 250x122 e-ink display that retains the image without power.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCK', role: 'clock'  },
      { name: 'SDI', role: 'data'   },
      { name: 'CS',  role: 'enable' },
      { name: 'RST', role: 'reset'  },
    ],
    model: {
      kind: 'display',
      size: [1.4, 0.08, 0.85],
      colors: { body: '#f0f0f0', accent: '#333333', detail: '#cccccc' },
    },
  },
  {
    id: 'neopixel-ring-12',
    name: 'NeoPixel Ring 12 LED',
    category: 'displays',
    description: 'Circular ring of 12 WS2812B individually addressable RGB LEDs on a PCB.',
    pins: [
      { name: '5V',  role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DIN', role: 'signal' },
    ],
    model: {
      kind: 'display',
      size: [1.0, 0.08, 1.0],
      colors: { body: '#17171c', accent: '#ff7759', detail: '#555555' },
    },
  },

  // ── SENSORS ──────────────────────────────────────────────────────────────
  {
    id: 'ldr-module',
    name: 'LDR Light Sensor Module',
    category: 'sensors',
    description: 'Analog light-dependent resistor module that outputs higher voltage in brighter light.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.6, 0.08, 0.45],
      colors: { body: '#1a5276', accent: '#ffd700', detail: '#0d3349' },
    },
  },
  {
    id: 'pir-hc-sr501',
    name: 'PIR Motion HC-SR501',
    category: 'sensors',
    description: 'Passive infrared motion sensor that detects movement of warm bodies up to 7 meters.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.35, 0.65],
      colors: { body: '#f5f5f0', accent: '#ccccaa', detail: '#888877' },
    },
  },
  {
    id: 'ultrasonic-hcsr04',
    name: 'HC-SR04 Ultrasonic',
    category: 'sensors',
    description: 'Ultrasonic distance sensor that measures range from 2 cm to 400 cm accurately.',
    pins: [
      { name: 'VCC',   role: 'power'  },
      { name: 'GND',   role: 'ground' },
      { name: 'TRIG',  role: 'signal' },
      { name: 'ECHO',  role: 'signal' },
    ],
    model: {
      kind: 'sensor',
      size: [1.0, 0.14, 0.55],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#f0f0f0' },
    },
  },
  {
    id: 'dht11',
    name: 'DHT11 Temp & Humidity',
    category: 'sensors',
    description: 'Digital temperature and humidity sensor accurate to ±2°C and ±5% RH.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DAT', role: 'data'   },
    ],
    model: {
      kind: 'sensor',
      size: [0.5, 0.2, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#ffffff' },
    },
  },
  {
    id: 'dht22',
    name: 'DHT22 Temp & Humidity',
    category: 'sensors',
    description: 'More accurate digital temperature and humidity sensor with ±0.5°C tolerance.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DAT', role: 'data'   },
    ],
    model: {
      kind: 'sensor',
      size: [0.55, 0.22, 0.5],
      colors: { body: '#f5f5f0', accent: '#ccccaa', detail: '#888888' },
    },
  },
  {
    id: 'bmp280',
    name: 'BMP280 Pressure Sensor',
    category: 'sensors',
    description: 'Digital barometric pressure and temperature sensor communicating over I2C or SPI.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
    ],
    model: {
      kind: 'sensor',
      size: [0.55, 0.08, 0.45],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'mpu6050',
    name: 'MPU-6050 IMU',
    category: 'sensors',
    description: 'Six-axis IMU combining a 3-axis gyroscope and 3-axis accelerometer on one chip.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
      { name: 'INT', role: 'signal' },
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.08, 0.45],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#555555' },
    },
  },
  {
    id: 'hmc5883l',
    name: 'HMC5883L Compass',
    category: 'sensors',
    description: 'Three-axis digital compass module that measures magnetic field direction.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
    ],
    model: {
      kind: 'sensor',
      size: [0.55, 0.08, 0.4],
      colors: { body: '#17171c', accent: '#4444aa', detail: '#333333' },
    },
  },
  {
    id: 'soil-moisture',
    name: 'Soil Moisture Sensor',
    category: 'sensors',
    description: 'Capacitive or resistive probe that measures soil water content for plant monitoring.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.5, 0.08, 1.2],
      colors: { body: '#5d4e37', accent: '#888866', detail: '#a08060' },
    },
  },
  {
    id: 'mq2-gas',
    name: 'MQ-2 Gas Sensor',
    category: 'sensors',
    description: 'Detects combustible gases, smoke, and LPG concentrations in the air.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.25, 0.65],
      colors: { body: '#1a5276', accent: '#888888', detail: '#c0c0c0' },
    },
  },
  {
    id: 'flame-sensor',
    name: 'Flame Sensor Module',
    category: 'sensors',
    description: 'Infrared flame detector that senses fire or open flame within 100 cm range.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.6, 0.08, 0.45],
      colors: { body: '#17171c', accent: '#ff7700', detail: '#333333' },
    },
  },
  {
    id: 'sound-sensor',
    name: 'Sound Detection Sensor',
    category: 'sensors',
    description: 'Microphone-based module that detects sound presence or measures volume level.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.6, 0.1, 0.45],
      colors: { body: '#1a5276', accent: '#aaaaaa', detail: '#555577' },
    },
  },
  {
    id: 'ir-receiver',
    name: 'IR Receiver Module',
    category: 'sensors',
    description: 'Receives 38 kHz infrared remote control signals and outputs them as digital pulses.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'signal' },
    ],
    model: {
      kind: 'sensor',
      size: [0.45, 0.15, 0.35],
      colors: { body: '#17171c', accent: '#333333', detail: '#555555' },
    },
  },
  {
    id: 'hall-effect-sensor',
    name: 'Hall Effect Sensor',
    category: 'sensors',
    description: 'Detects the presence of a magnetic field and outputs a digital or analog signal.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'signal' },
    ],
    model: {
      kind: 'sensor',
      size: [0.4, 0.08, 0.35],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#444444' },
    },
  },
  {
    id: 'tcs3200-color',
    name: 'TCS3200 Color Sensor',
    category: 'sensors',
    description: 'Detects RGB color intensity using photodiode arrays and a frequency output.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'S0',  role: 'signal' },
      { name: 'S2',  role: 'signal' },
      { name: 'OUT', role: 'output' },
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.1, 0.6],
      colors: { body: '#f5f5f0', accent: '#ff0066', detail: '#cccccc' },
    },
  },
  {
    id: 'hx711-loadcell',
    name: 'HX711 Load Cell Amp',
    category: 'sensors',
    description: 'Precision 24-bit ADC amplifier module for load cells and weight measurement.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DT',  role: 'data'   },
      { name: 'SCK', role: 'clock'  },
    ],
    model: {
      kind: 'sensor',
      size: [0.6, 0.08, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'gps-neo6m',
    name: 'GPS Module NEO-6M',
    category: 'sensors',
    description: 'GPS receiver module that outputs NMEA sentences for position and time data.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'TX',  role: 'tx'     },
      { name: 'RX',  role: 'rx'     },
    ],
    model: {
      kind: 'sensor',
      size: [0.75, 0.1, 0.65],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#4444aa' },
    },
  },
  {
    id: 'rc522-rfid',
    name: 'RC522 RFID Module',
    category: 'sensors',
    description: 'Reads and writes 13.56 MHz MIFARE RFID cards and key fobs over SPI.',
    pins: [
      { name: '3V3',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'SCK',  role: 'clock'  },
      { name: 'MOSI', role: 'data'   },
      { name: 'MISO', role: 'data'   },
      { name: 'CS',   role: 'enable' },
    ],
    model: {
      kind: 'sensor',
      size: [0.9, 0.08, 0.75],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'max30102-pulse',
    name: 'MAX30102 Pulse Oximeter',
    category: 'sensors',
    description: 'Optical heart-rate and blood oxygen SpO2 sensor using red and IR LEDs.',
    pins: [
      { name: 'VIN', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
      { name: 'INT', role: 'signal' },
    ],
    model: {
      kind: 'sensor',
      size: [0.55, 0.08, 0.45],
      colors: { body: '#c2362f', accent: '#ff2200', detail: '#333333' },
    },
  },
  {
    id: 'acs712-current',
    name: 'ACS712 Current Sensor',
    category: 'sensors',
    description: 'Hall-effect linear current sensor that measures AC or DC current up to 30 A.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'analog' },
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.1, 0.45],
      colors: { body: '#1a5276', accent: '#aaaaaa', detail: '#0d3349' },
    },
  },
  {
    id: 'water-level-sensor',
    name: 'Water Level Sensor',
    category: 'sensors',
    description: 'Detects the presence or depth of water using exposed conductor traces.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'S',   role: 'analog' },
    ],
    model: {
      kind: 'sensor',
      size: [0.45, 0.07, 1.1],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#c0c0c0' },
    },
  },
  {
    id: 'sw420-vibration',
    name: 'SW-420 Vibration Sensor',
    category: 'sensors',
    description: 'Spring-based vibration and tilt sensor module that triggers on shock or movement.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.5, 0.1, 0.38],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'line-tracker',
    name: 'Line Tracking Sensor',
    category: 'sensors',
    description: 'IR reflectance sensor that detects black lines on white surfaces for robot navigation.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.55, 0.08, 0.35],
      colors: { body: '#17171c', accent: '#ff4444', detail: '#222222' },
    },
  },
  {
    id: 'rain-sensor',
    name: 'Rain Sensor Module',
    category: 'sensors',
    description: 'Detects rainfall on its sensor board using resistance change between conductive pads.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'AO',  role: 'analog' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.65, 0.08, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'tilt-ball-sensor',
    name: 'Tilt Ball Switch',
    category: 'sensors',
    description: 'Simple tilt sensor with a metal ball that closes a circuit when tilted.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DO',  role: 'digital'},
    ],
    model: {
      kind: 'sensor',
      size: [0.4, 0.15, 0.35],
      colors: { body: '#17171c', accent: '#888888', detail: '#cccccc' },
    },
  },
  {
    id: 'tmp36-temp',
    name: 'TMP36 Temperature Sensor',
    category: 'sensors',
    description: 'Analog temperature sensor outputting a voltage proportional to temperature in Celsius.',
    pins: [
      { name: 'VS',  role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'analog' },
    ],
    model: {
      kind: 'sensor',
      size: [0.35, 0.3, 0.35],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#555555' },
    },
  },
  {
    id: 'thermistor-ntc',
    name: 'NTC Thermistor',
    category: 'sensors',
    description: 'Negative temperature coefficient resistor whose resistance falls with rising temperature.',
    pins: [
      { name: 'A', role: 'analog' },
      { name: 'B', role: 'analog' },
    ],
    model: {
      kind: 'sensor',
      size: [0.3, 0.3, 0.3],
      colors: { body: '#cc4400', accent: '#ffaa66', detail: '#884400' },
    },
  },
  {
    id: 'fsr-pressure',
    name: 'FSR Force Sensor',
    category: 'sensors',
    description: 'Force-sensing resistor that decreases resistance when pressure is applied to it.',
    pins: [
      { name: 'A', role: 'analog' },
      { name: 'B', role: 'analog' },
    ],
    model: {
      kind: 'sensor',
      size: [0.6, 0.05, 0.6],
      colors: { body: '#cc4400', accent: '#ffaa00', detail: '#884400' },
    },
  },

  // ── ACTUATORS ────────────────────────────────────────────────────────────
  {
    id: 'led-5mm-red',
    name: '5mm LED Red',
    category: 'actuators',
    description: 'Standard 5mm red light-emitting diode, forward voltage about 2V at 20mA.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'dome',
      size: [0.3, 0.3, 0.3],
      colors: { body: '#cc0000', accent: '#ff4444', detail: '#880000' },
    },
  },
  {
    id: 'led-5mm-green',
    name: '5mm LED Green',
    category: 'actuators',
    description: 'Standard 5mm green light-emitting diode for status indication and projects.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'dome',
      size: [0.3, 0.3, 0.3],
      colors: { body: '#00aa00', accent: '#44ff44', detail: '#006600' },
    },
  },
  {
    id: 'led-5mm-blue',
    name: '5mm LED Blue',
    category: 'actuators',
    description: 'Standard 5mm blue light-emitting diode with forward voltage around 3.2V.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'dome',
      size: [0.3, 0.3, 0.3],
      colors: { body: '#0044cc', accent: '#4488ff', detail: '#002288' },
    },
  },
  {
    id: 'rgb-led-common-cathode',
    name: 'RGB LED Common Cathode',
    category: 'actuators',
    description: 'Three-color LED with separate red, green, blue anodes sharing one common cathode.',
    pins: [
      { name: 'R',   role: 'signal' },
      { name: 'G',   role: 'signal' },
      { name: 'B',   role: 'signal' },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'dome',
      size: [0.35, 0.35, 0.35],
      colors: { body: '#ffffff', accent: '#ff00ff', detail: '#888888' },
    },
  },
  {
    id: 'ws2812b-strip',
    name: 'WS2812B LED Strip',
    category: 'actuators',
    description: 'Individually addressable RGB LED strip with integrated controller in each LED.',
    pins: [
      { name: '5V',  role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DIN', role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [2.0, 0.06, 0.35],
      colors: { body: '#17171c', accent: '#ff7759', detail: '#444444' },
    },
  },
  {
    id: 'sg90-servo',
    name: 'SG90 Micro Servo',
    category: 'actuators',
    description: 'Lightweight 9g servo motor capable of 180-degree rotation, popular for robotics.',
    pins: [
      { name: 'VCC',    role: 'power'  },
      { name: 'GND',    role: 'ground' },
      { name: 'SIGNAL', role: 'pwm'    },
    ],
    model: {
      kind: 'motor',
      size: [0.55, 0.45, 0.35],
      colors: { body: '#dddddd', accent: '#333333', detail: '#aaaaaa' },
    },
  },
  {
    id: 'mg996r-servo',
    name: 'MG996R Metal Servo',
    category: 'actuators',
    description: 'High-torque metal gear servo producing 9.4 kg/cm of torque for heavy-duty arms.',
    pins: [
      { name: 'VCC',    role: 'power'  },
      { name: 'GND',    role: 'ground' },
      { name: 'SIGNAL', role: 'pwm'    },
    ],
    model: {
      kind: 'motor',
      size: [0.65, 0.55, 0.4],
      colors: { body: '#222222', accent: '#555555', detail: '#aaaaaa' },
    },
  },
  {
    id: 'dc-motor-130',
    name: 'DC Motor 130',
    category: 'actuators',
    description: 'Small 3V-6V brushed DC motor commonly used in toy cars and fan projects.',
    pins: [
      { name: 'M+', role: 'power'  },
      { name: 'M-', role: 'ground' },
    ],
    model: {
      kind: 'motor',
      size: [0.5, 0.5, 0.8],
      colors: { body: '#888888', accent: '#cccccc', detail: '#444444' },
    },
  },
  {
    id: 'stepper-28byj48',
    name: '28BYJ-48 Stepper Motor',
    category: 'actuators',
    description: 'Five-wire unipolar stepper motor with a 1/64 gear reduction used with ULN2003.',
    pins: [
      { name: 'IN1', role: 'signal' },
      { name: 'IN2', role: 'signal' },
      { name: 'IN3', role: 'signal' },
      { name: 'IN4', role: 'signal' },
      { name: 'VCC', role: 'power'  },
    ],
    model: {
      kind: 'motor',
      size: [0.7, 0.7, 0.85],
      colors: { body: '#1f6fb2', accent: '#aaaaaa', detail: '#0d3349' },
    },
  },
  {
    id: 'nema17-stepper',
    name: 'NEMA 17 Stepper Motor',
    category: 'actuators',
    description: 'Bipolar stepper motor with 200 steps per revolution widely used in 3D printers.',
    pins: [
      { name: 'A+', role: 'signal' },
      { name: 'A-', role: 'signal' },
      { name: 'B+', role: 'signal' },
      { name: 'B-', role: 'signal' },
    ],
    model: {
      kind: 'motor',
      size: [1.1, 1.1, 1.2],
      colors: { body: '#333333', accent: '#888888', detail: '#555555' },
    },
  },
  {
    id: 'passive-buzzer',
    name: 'Passive Buzzer',
    category: 'actuators',
    description: 'Passive piezoelectric buzzer that requires a PWM signal to produce different tones.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'sphere',
      size: [0.45, 0.25, 0.45],
      colors: { body: '#17171c', accent: '#555555', detail: '#888888' },
    },
  },
  {
    id: 'active-buzzer',
    name: 'Active Buzzer',
    category: 'actuators',
    description: 'Active piezoelectric buzzer with built-in oscillator that buzzes at a fixed frequency.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'sphere',
      size: [0.45, 0.25, 0.45],
      colors: { body: '#222222', accent: '#666666', detail: '#aaaaaa' },
    },
  },
  {
    id: 'relay-1ch',
    name: '1-Channel Relay Module',
    category: 'actuators',
    description: 'Single-channel relay board that switches high-voltage loads with a 5V logic signal.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'IN',  role: 'signal' },
      { name: 'COM', role: 'output' },
      { name: 'NO',  role: 'output' },
      { name: 'NC',  role: 'output' },
    ],
    model: {
      kind: 'module',
      size: [0.85, 0.2, 0.65],
      colors: { body: '#1a5276', accent: '#ff7759', detail: '#0d3349' },
    },
  },
  {
    id: 'relay-4ch',
    name: '4-Channel Relay Module',
    category: 'actuators',
    description: 'Four independent relay switches on one board for controlling multiple high-voltage devices.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'IN1', role: 'signal' },
      { name: 'IN2', role: 'signal' },
      { name: 'IN3', role: 'signal' },
      { name: 'IN4', role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [1.8, 0.2, 0.65],
      colors: { body: '#1a5276', accent: '#ff7759', detail: '#0d3349' },
    },
  },
  {
    id: 'laser-diode-module',
    name: 'Laser Diode Module',
    category: 'actuators',
    description: '5mW 650nm red laser diode module producing a focused beam for pointing or sensing.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'S',   role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [0.45, 0.45, 0.6],
      colors: { body: '#17171c', accent: '#ff2200', detail: '#444444' },
    },
  },
  {
    id: 'vibration-motor',
    name: 'Vibration Motor Module',
    category: 'actuators',
    description: 'Coin-style vibration motor module that creates haptic feedback when energized.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'IN',  role: 'signal' },
    ],
    model: {
      kind: 'motor',
      size: [0.5, 0.15, 0.5],
      colors: { body: '#888888', accent: '#cccccc', detail: '#555555' },
    },
  },
  {
    id: 'mini-water-pump',
    name: 'Mini Water Pump',
    category: 'actuators',
    description: 'Small submersible DC water pump for irrigation or fluid movement projects.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'motor',
      size: [0.7, 0.6, 0.55],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'dc-fan-5v',
    name: '5V DC Cooling Fan',
    category: 'actuators',
    description: 'Small 30mm x 30mm 5V brushless DC fan used for cooling components.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'motor',
      size: [0.8, 0.25, 0.8],
      colors: { body: '#222222', accent: '#555555', detail: '#888888' },
    },
  },
  {
    id: 'solenoid-valve',
    name: 'Solenoid Valve',
    category: 'actuators',
    description: 'Electrically controlled valve that opens and closes to control fluid or air flow.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'motor',
      size: [0.7, 0.9, 0.7],
      colors: { body: '#333333', accent: '#888888', detail: '#555555' },
    },
  },

  // ── ICs & DRIVERS ─────────────────────────────────────────────────────────
  {
    id: 'l298n-driver',
    name: 'L298N Motor Driver',
    category: 'ics',
    description: 'Dual H-bridge motor driver module capable of driving two DC motors or one stepper.',
    pins: [
      { name: 'ENA',  role: 'enable'  },
      { name: 'IN1',  role: 'signal'  },
      { name: 'IN2',  role: 'signal'  },
      { name: 'IN3',  role: 'signal'  },
      { name: 'IN4',  role: 'signal'  },
      { name: 'ENB',  role: 'enable'  },
    ],
    model: {
      kind: 'module',
      size: [1.1, 0.3, 0.85],
      colors: { body: '#17171c', accent: '#ff7759', detail: '#888888' },
    },
  },
  {
    id: 'uln2003-driver',
    name: 'ULN2003 Stepper Driver',
    category: 'ics',
    description: 'Seven-channel Darlington transistor array module for driving the 28BYJ-48 stepper.',
    pins: [
      { name: 'IN1', role: 'signal' },
      { name: 'IN2', role: 'signal' },
      { name: 'IN3', role: 'signal' },
      { name: 'IN4', role: 'signal' },
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'module',
      size: [0.75, 0.1, 0.55],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'a4988-stepper',
    name: 'A4988 Stepper Driver',
    category: 'ics',
    description: 'Microstepping bipolar stepper motor driver with up to 1/16 step resolution.',
    pins: [
      { name: 'VMOT', role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'STEP', role: 'signal' },
      { name: 'DIR',  role: 'signal' },
      { name: 'EN',   role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.6, 0.12, 0.5],
      colors: { body: '#c2362f', accent: '#ff9900', detail: '#880000' },
    },
  },
  {
    id: 'drv8825-stepper',
    name: 'DRV8825 Stepper Driver',
    category: 'ics',
    description: 'High-current 1/32 microstepping stepper driver with adjustable current limiting.',
    pins: [
      { name: 'VMOT', role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'STEP', role: 'signal' },
      { name: 'DIR',  role: 'signal' },
      { name: 'EN',   role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.6, 0.12, 0.5],
      colors: { body: '#4a0080', accent: '#aa44ff', detail: '#220044' },
    },
  },
  {
    id: '74hc595-shift',
    name: '74HC595 Shift Register',
    category: 'ics',
    description: 'Eight-bit serial-in parallel-out shift register that expands GPIO with 3 pins.',
    pins: [
      { name: 'VCC',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'SER',  role: 'data'   },
      { name: 'SRCLK',role: 'clock'  },
      { name: 'RCLK', role: 'clock'  },
      { name: 'OE',   role: 'enable' },
    ],
    model: {
      kind: 'chip',
      size: [0.55, 0.2, 0.35],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'ne555-timer',
    name: 'NE555 Timer IC',
    category: 'ics',
    description: 'Classic versatile timer IC usable in monostable, bistable, and astable modes.',
    pins: [
      { name: 'VCC',   role: 'power'  },
      { name: 'GND',   role: 'ground' },
      { name: 'OUT',   role: 'output' },
      { name: 'TRIG',  role: 'input'  },
      { name: 'THR',   role: 'input'  },
      { name: 'RST',   role: 'reset'  },
    ],
    model: {
      kind: 'chip',
      size: [0.45, 0.2, 0.3],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'lm358-opamp',
    name: 'LM358 Op-Amp',
    category: 'ics',
    description: 'Dual general-purpose operational amplifier IC for signal processing and comparators.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'IN+', role: 'input'  },
      { name: 'IN-', role: 'input'  },
      { name: 'OUT', role: 'output' },
    ],
    model: {
      kind: 'chip',
      size: [0.45, 0.2, 0.3],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: '7805-regulator',
    name: '7805 Voltage Regulator',
    category: 'ics',
    description: 'Linear voltage regulator that outputs a stable 5V from 7V-35V input supplies.',
    pins: [
      { name: 'IN',  role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'output' },
    ],
    model: {
      kind: 'chip',
      size: [0.35, 0.4, 0.25],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#555555' },
    },
  },
  {
    id: 'irf520-mosfet',
    name: 'IRF520 MOSFET Module',
    category: 'ics',
    description: 'N-channel MOSFET driver module that switches high-current loads from a logic signal.',
    pins: [
      { name: 'VIN', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SIG', role: 'signal' },
      { name: 'V+',  role: 'output' },
      { name: 'V-',  role: 'output' },
    ],
    model: {
      kind: 'module',
      size: [0.55, 0.12, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: '2n2222-npn',
    name: '2N2222 NPN Transistor',
    category: 'ics',
    description: 'General-purpose NPN bipolar junction transistor for switching and amplification up to 600mA.',
    pins: [
      { name: 'B', role: 'input'  },
      { name: 'C', role: 'output' },
      { name: 'E', role: 'ground' },
    ],
    model: {
      kind: 'chip',
      size: [0.28, 0.35, 0.28],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'ads1115-adc',
    name: 'ADS1115 ADC Module',
    category: 'ics',
    description: 'Sixteen-bit four-channel ADC with programmable gain amplifier over I2C interface.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
      { name: 'A0',  role: 'analog' },
      { name: 'A1',  role: 'analog' },
    ],
    model: {
      kind: 'module',
      size: [0.65, 0.1, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'pcf8574-expander',
    name: 'PCF8574 I2C Expander',
    category: 'ics',
    description: 'Eight-bit I2C GPIO expander that adds eight additional I/O pins with configurable address.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCL', role: 'clock'  },
      { name: 'SDA', role: 'data'   },
      { name: 'INT', role: 'signal' },
    ],
    model: {
      kind: 'chip',
      size: [0.5, 0.2, 0.35],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#444444' },
    },
  },
  {
    id: 'mcp3008-adc',
    name: 'MCP3008 SPI ADC',
    category: 'ics',
    description: 'Ten-bit eight-channel SPI analog-to-digital converter for adding analog inputs.',
    pins: [
      { name: 'VDD',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'CLK',  role: 'clock'  },
      { name: 'DOUT', role: 'data'   },
      { name: 'DIN',  role: 'data'   },
      { name: 'CS',   role: 'enable' },
    ],
    model: {
      kind: 'chip',
      size: [0.55, 0.2, 0.38],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'l293d-driver',
    name: 'L293D Motor Driver IC',
    category: 'ics',
    description: 'Quad half-bridge motor driver IC that controls two DC motors with built-in diodes.',
    pins: [
      { name: 'VCC1', role: 'power'  },
      { name: 'VCC2', role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'EN1',  role: 'enable' },
      { name: 'IN1',  role: 'signal' },
      { name: 'IN2',  role: 'signal' },
    ],
    model: {
      kind: 'chip',
      size: [0.6, 0.25, 0.4],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },

  // ── PASSIVES ─────────────────────────────────────────────────────────────
  {
    id: 'resistor-axial',
    name: 'Resistor (Axial)',
    category: 'passives',
    description: 'Carbon film or metal film axial-lead resistor in values from 1Ω to 10MΩ.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.5, 0.14, 0.14],
      colors: { body: '#c8a200', accent: '#8b4513', detail: '#ffcc00' },
    },
  },
  {
    id: 'electrolytic-cap',
    name: 'Electrolytic Capacitor',
    category: 'passives',
    description: 'Polarized aluminum electrolytic capacitor for filtering and energy storage.',
    pins: [
      { name: '+', role: 'power'  },
      { name: '-', role: 'ground' },
    ],
    model: {
      kind: 'cylinder',
      size: [0.3, 0.5, 0.3],
      colors: { body: '#222266', accent: '#cccccc', detail: '#111144' },
    },
  },
  {
    id: 'ceramic-cap',
    name: 'Ceramic Capacitor',
    category: 'passives',
    description: 'Non-polarized ceramic disc capacitor for decoupling and high-frequency filtering.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.3, 0.18, 0.18],
      colors: { body: '#c8a200', accent: '#ffcc00', detail: '#8b4513' },
    },
  },
  {
    id: 'potentiometer',
    name: 'Potentiometer 10K',
    category: 'passives',
    description: 'Three-terminal rotary potentiometer providing adjustable resistance from 0 to 10KΩ.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'OUT', role: 'analog' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.5, 0.35, 0.5],
      colors: { body: '#1a1a2e', accent: '#888888', detail: '#cccccc' },
    },
  },
  {
    id: 'trimmer-pot',
    name: 'Trimmer Potentiometer',
    category: 'passives',
    description: 'Small adjustable screwdriver-set potentiometer for circuit calibration.',
    pins: [
      { name: 'A',   role: 'power'  },
      { name: 'W',   role: 'analog' },
      { name: 'B',   role: 'ground' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.3, 0.25, 0.3],
      colors: { body: '#1a5276', accent: '#aaaaaa', detail: '#0d3349' },
    },
  },
  {
    id: 'inductor-axial',
    name: 'Inductor (Axial)',
    category: 'passives',
    description: 'Axial-lead wire-wound inductor for energy storage, filtering, and RF applications.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.5, 0.18, 0.18],
      colors: { body: '#228822', accent: '#aaffaa', detail: '#116611' },
    },
  },
  {
    id: 'diode-1n4007',
    name: '1N4007 Rectifier Diode',
    category: 'passives',
    description: 'General-purpose silicon rectifier diode rated for 1A at 1000V peak inverse voltage.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.5, 0.16, 0.16],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#888888' },
    },
  },
  {
    id: 'zener-diode',
    name: 'Zener Diode',
    category: 'passives',
    description: 'Voltage reference diode that conducts in reverse at its specific breakdown voltage.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.45, 0.15, 0.15],
      colors: { body: '#17171c', accent: '#888888', detail: '#cccccc' },
    },
  },
  {
    id: 'schottky-diode',
    name: 'Schottky Diode 1N5819',
    category: 'passives',
    description: 'Fast-switching low forward-voltage Schottky diode ideal for reverse-polarity protection.',
    pins: [
      { name: 'A', role: 'power'  },
      { name: 'K', role: 'ground' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.45, 0.16, 0.16],
      colors: { body: '#884400', accent: '#ffaa00', detail: '#cc6600' },
    },
  },
  {
    id: 'crystal-16mhz',
    name: '16 MHz Crystal',
    category: 'passives',
    description: 'Quartz crystal oscillator used to provide a precise 16 MHz clock to microcontrollers.',
    pins: [
      { name: 'X1', role: 'clock' },
      { name: 'X2', role: 'clock' },
    ],
    model: {
      kind: 'cylinder',
      size: [0.2, 0.5, 0.2],
      colors: { body: '#c8a200', accent: '#ffcc00', detail: '#8b4513' },
    },
  },
  {
    id: 'polyfuse',
    name: 'Polyfuse / Resettable Fuse',
    category: 'passives',
    description: 'Self-resetting PPTC fuse that trips on overcurrent and recovers when cooled.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.38, 0.12, 0.12],
      colors: { body: '#ffcc00', accent: '#ff7700', detail: '#cc9900' },
    },
  },
  {
    id: 'varistor-mov',
    name: 'Varistor (MOV)',
    category: 'passives',
    description: 'Metal oxide varistor that clamps voltage spikes to protect circuits from transients.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.4, 0.25, 0.4],
      colors: { body: '#1a8822', accent: '#aaffaa', detail: '#116611' },
    },
  },

  // ── INPUTS ───────────────────────────────────────────────────────────────
  {
    id: 'push-button',
    name: 'Push Button (Tactile)',
    category: 'inputs',
    description: 'Momentary tactile push button switch that closes a circuit when pressed.',
    pins: [
      { name: 'A1', role: 'input'  },
      { name: 'A2', role: 'input'  },
      { name: 'B1', role: 'ground' },
      { name: 'B2', role: 'ground' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.35, 0.3, 0.35],
      colors: { body: '#17171c', accent: '#cccccc', detail: '#888888' },
    },
  },
  {
    id: 'slide-switch',
    name: 'Slide Switch',
    category: 'inputs',
    description: 'Three-terminal slide switch for toggling between two positions in circuits.',
    pins: [
      { name: 'COM', role: 'signal' },
      { name: 'A',   role: 'input'  },
      { name: 'B',   role: 'input'  },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.45, 0.2, 0.3],
      colors: { body: '#17171c', accent: '#888888', detail: '#cccccc' },
    },
  },
  {
    id: 'toggle-switch',
    name: 'Toggle Switch',
    category: 'inputs',
    description: 'Lever toggle switch that mechanically stays in the on or off position.',
    pins: [
      { name: 'COM', role: 'signal' },
      { name: 'NO',  role: 'input'  },
      { name: 'NC',  role: 'input'  },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.4, 0.55, 0.35],
      colors: { body: '#888888', accent: '#17171c', detail: '#cccccc' },
    },
  },
  {
    id: 'dip-switch-4',
    name: '4-Way DIP Switch',
    category: 'inputs',
    description: 'Four independent single-pole switches in a DIP package for configuration settings.',
    pins: [
      { name: 'S1A', role: 'input'  },
      { name: 'S1B', role: 'input'  },
      { name: 'S2A', role: 'input'  },
      { name: 'S2B', role: 'input'  },
    ],
    model: {
      kind: 'chip',
      size: [0.6, 0.2, 0.35],
      colors: { body: '#17171c', accent: '#cccccc', detail: '#ff0000' },
    },
  },
  {
    id: 'joystick-module',
    name: 'Analog Joystick Module',
    category: 'inputs',
    description: 'Dual-axis analog joystick with a center push button for game-style control input.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'VRX', role: 'analog' },
      { name: 'VRY', role: 'analog' },
      { name: 'SW',  role: 'digital'},
    ],
    model: {
      kind: 'module',
      size: [0.7, 0.45, 0.7],
      colors: { body: '#17171c', accent: '#888888', detail: '#aaaaaa' },
    },
  },
  {
    id: 'keypad-4x4',
    name: '4x4 Matrix Keypad',
    category: 'inputs',
    description: 'Sixteen-key matrix membrane keypad with rows and columns for button scanning.',
    pins: [
      { name: 'R1', role: 'signal' },
      { name: 'R2', role: 'signal' },
      { name: 'C1', role: 'signal' },
      { name: 'C2', role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [1.1, 0.05, 1.1],
      colors: { body: '#1a1a2e', accent: '#aaaaaa', detail: '#555577' },
    },
  },
  {
    id: 'rotary-encoder',
    name: 'Rotary Encoder Module',
    category: 'inputs',
    description: 'Incremental rotary encoder with push button that detects rotation direction and clicks.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'CLK', role: 'clock'  },
      { name: 'DT',  role: 'data'   },
      { name: 'SW',  role: 'digital'},
    ],
    model: {
      kind: 'module',
      size: [0.6, 0.5, 0.6],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#888888' },
    },
  },
  {
    id: 'limit-switch',
    name: 'Limit Switch',
    category: 'inputs',
    description: 'Mechanical switch that triggers when a moving part reaches its travel boundary.',
    pins: [
      { name: 'COM', role: 'signal' },
      { name: 'NO',  role: 'input'  },
      { name: 'NC',  role: 'input'  },
    ],
    model: {
      kind: 'module',
      size: [0.7, 0.45, 0.4],
      colors: { body: '#888888', accent: '#ff2200', detail: '#555555' },
    },
  },
  {
    id: 'reed-switch',
    name: 'Reed Switch',
    category: 'inputs',
    description: 'Magnetically actuated glass encapsulated switch that closes in the presence of a magnet.',
    pins: [
      { name: 'A', role: 'input' },
      { name: 'B', role: 'input' },
    ],
    model: {
      kind: 'passive-axial',
      size: [0.55, 0.15, 0.15],
      colors: { body: '#aaaaaa', accent: '#cccccc', detail: '#888888' },
    },
  },
  {
    id: 'ttp223-touch',
    name: 'TTP223 Capacitive Touch',
    category: 'inputs',
    description: 'Capacitive touch sensor module that detects a fingertip without mechanical contact.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SIG', role: 'digital'},
    ],
    model: {
      kind: 'module',
      size: [0.55, 0.08, 0.45],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'membrane-keypad-1x4',
    name: 'Membrane Keypad 1x4',
    category: 'inputs',
    description: 'Flat four-button membrane keypad strip for simple menu or media control input.',
    pins: [
      { name: 'K1', role: 'signal' },
      { name: 'K2', role: 'signal' },
      { name: 'K3', role: 'signal' },
      { name: 'K4', role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [1.4, 0.04, 0.4],
      colors: { body: '#1a1a2e', accent: '#aaaaaa', detail: '#555577' },
    },
  },

  // ── POWER & COMMS ─────────────────────────────────────────────────────────
  {
    id: '9v-battery-clip',
    name: '9V Battery with Clip',
    category: 'power-comms',
    description: 'Standard PP3 9V alkaline battery with snap connector for portable power projects.',
    pins: [
      { name: '+', role: 'power'  },
      { name: '-', role: 'ground' },
    ],
    model: {
      kind: 'cylinder',
      size: [0.55, 1.1, 0.55],
      colors: { body: '#222266', accent: '#ffcc00', detail: '#111144' },
    },
  },
  {
    id: 'aa-battery-holder',
    name: 'AA Battery Holder 4x',
    category: 'power-comms',
    description: 'Four-AA battery holder providing 6V from standard alkaline cells with leads.',
    pins: [
      { name: '+', role: 'power'  },
      { name: '-', role: 'ground' },
    ],
    model: {
      kind: 'module',
      size: [1.5, 0.45, 0.55],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'lipo-battery-1s',
    name: 'LiPo Battery 1S 1000mAh',
    category: 'power-comms',
    description: 'Single-cell 3.7V lithium polymer battery for compact portable power applications.',
    pins: [
      { name: '+', role: 'power'  },
      { name: '-', role: 'ground' },
    ],
    model: {
      kind: 'module',
      size: [1.1, 0.25, 0.6],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'breadboard-psu',
    name: 'Breadboard Power Supply',
    category: 'power-comms',
    description: 'Plug-in breadboard power module providing selectable 3.3V and 5V rails.',
    pins: [
      { name: '5V',   role: 'power'  },
      { name: '3V3',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
    ],
    model: {
      kind: 'module',
      size: [0.85, 0.3, 0.55],
      colors: { body: '#c2362f', accent: '#ffcc00', detail: '#880000' },
    },
  },
  {
    id: 'barrel-jack',
    name: 'DC Barrel Jack',
    category: 'power-comms',
    description: 'Standard 5.5mm/2.1mm DC power barrel socket for connecting power adapters.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
    ],
    model: {
      kind: 'connector',
      size: [0.4, 0.3, 0.4],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'screw-terminal-2pin',
    name: '2-Pin Screw Terminal',
    category: 'power-comms',
    description: 'Two-position PCB-mount screw terminal block for secure wire connections.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'connector',
      size: [0.5, 0.3, 0.35],
      colors: { body: '#008800', accent: '#aaaaaa', detail: '#005500' },
    },
  },
  {
    id: 'hc05-bluetooth',
    name: 'HC-05 Bluetooth Module',
    category: 'power-comms',
    description: 'Classic Bluetooth serial module for wireless UART communication up to 10 meters.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'TX',  role: 'tx'     },
      { name: 'RX',  role: 'rx'     },
    ],
    model: {
      kind: 'module',
      size: [0.75, 0.12, 0.5],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'esp01-wifi',
    name: 'ESP-01 WiFi Module',
    category: 'power-comms',
    description: 'Compact ESP8266-based WiFi module adding wireless connectivity via AT commands.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'TX',  role: 'tx'     },
      { name: 'RX',  role: 'rx'     },
      { name: 'RST', role: 'reset'  },
    ],
    model: {
      kind: 'module',
      size: [0.65, 0.1, 0.45],
      colors: { body: '#1a5276', accent: '#aaaaaa', detail: '#0d3349' },
    },
  },
  {
    id: 'nrf24l01-radio',
    name: 'NRF24L01 2.4GHz Radio',
    category: 'power-comms',
    description: 'Low-power 2.4GHz transceiver module for wireless communication over 100 meters.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'CE',  role: 'enable' },
      { name: 'CSN', role: 'enable' },
      { name: 'SCK', role: 'clock'  },
      { name: 'MOSI',role: 'data'   },
    ],
    model: {
      kind: 'module',
      size: [0.75, 0.1, 0.55],
      colors: { body: '#17171c', accent: '#00aaff', detail: '#333333' },
    },
  },
  {
    id: 'lora-ra02',
    name: 'LoRa Ra-02 Module',
    category: 'power-comms',
    description: 'SX1278 LoRa spread-spectrum radio module for long-range low-power IoT links.',
    pins: [
      { name: '3V3',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'SCK',  role: 'clock'  },
      { name: 'MISO', role: 'data'   },
      { name: 'MOSI', role: 'data'   },
      { name: 'NSS',  role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.85, 0.12, 0.55],
      colors: { body: '#1a5276', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'sim800l-gsm',
    name: 'SIM800L GSM Module',
    category: 'power-comms',
    description: 'Quad-band GSM/GPRS module for SMS, calls, and mobile data in embedded projects.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'TX',  role: 'tx'     },
      { name: 'RX',  role: 'rx'     },
      { name: 'RST', role: 'reset'  },
    ],
    model: {
      kind: 'module',
      size: [0.85, 0.12, 0.75],
      colors: { body: '#17171c', accent: '#888888', detail: '#444444' },
    },
  },
  {
    id: 'rs485-module',
    name: 'RS-485 Transceiver Module',
    category: 'power-comms',
    description: 'MAX485-based module for long-distance differential RS-485 serial communication.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'DI',  role: 'tx'     },
      { name: 'RO',  role: 'rx'     },
      { name: 'DE',  role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.7, 0.1, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
  {
    id: 'mcp2515-can',
    name: 'MCP2515 CAN Bus Module',
    category: 'power-comms',
    description: 'SPI-to-CAN controller module for connecting microcontrollers to a CAN bus network.',
    pins: [
      { name: 'VCC',  role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'SCK',  role: 'clock'  },
      { name: 'SI',   role: 'data'   },
      { name: 'SO',   role: 'data'   },
      { name: 'CS',   role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.8, 0.12, 0.55],
      colors: { body: '#1a5276', accent: '#aaaaaa', detail: '#0d3349' },
    },
  },
  {
    id: 'usb-host-shield',
    name: 'USB Host Shield Mini',
    category: 'power-comms',
    description: 'MAX3421E-based shield that lets an Arduino act as a USB host to connect USB devices.',
    pins: [
      { name: 'VCC', role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'SCK', role: 'clock'  },
      { name: 'MISO',role: 'data'   },
      { name: 'MOSI',role: 'data'   },
      { name: 'SS',  role: 'enable' },
    ],
    model: {
      kind: 'module',
      size: [0.75, 0.1, 0.55],
      colors: { body: '#c2362f', accent: '#ff7759', detail: '#880000' },
    },
  },

  // ── PROTOTYPING ───────────────────────────────────────────────────────────
  {
    id: 'breadboard-half',
    name: 'Half-Size Breadboard',
    category: 'prototyping',
    description: 'Four-hundred tie-point solderless breadboard for quick prototype circuit building.',
    pins: [
      { name: 'PWR+', role: 'power'  },
      { name: 'PWR-', role: 'ground' },
    ],
    model: {
      kind: 'breadboard',
      size: [2.2, 0.12, 1.3],
      colors: { body: '#f5f5f0', accent: '#cc0000', detail: '#0000cc' },
    },
  },
  {
    id: 'breadboard-full',
    name: 'Full-Size Breadboard',
    category: 'prototyping',
    description: 'Eight-hundred thirty tie-point solderless breadboard with dual power rails.',
    pins: [
      { name: 'PWR+', role: 'power'  },
      { name: 'PWR-', role: 'ground' },
    ],
    model: {
      kind: 'breadboard',
      size: [2.5, 0.12, 1.7],
      colors: { body: '#f5f5f0', accent: '#cc0000', detail: '#0000cc' },
    },
  },
  {
    id: 'breadboard-mini',
    name: 'Mini Breadboard',
    category: 'prototyping',
    description: 'One-hundred seventy tie-point mini breadboard for very compact prototype layouts.',
    pins: [
      { name: 'PWR+', role: 'power'  },
      { name: 'PWR-', role: 'ground' },
    ],
    model: {
      kind: 'breadboard',
      size: [1.3, 0.1, 0.85],
      colors: { body: '#f5f5f0', accent: '#cc0000', detail: '#0000cc' },
    },
  },
  {
    id: 'perfboard-5x7',
    name: 'Perfboard 5x7cm',
    category: 'prototyping',
    description: 'Five-by-seven centimeter copper-padded perfboard for soldering permanent circuits.',
    pins: [
      { name: 'PAD', role: 'signal' },
    ],
    model: {
      kind: 'breadboard',
      size: [1.8, 0.08, 1.3],
      colors: { body: '#3d1a00', accent: '#c8a200', detail: '#22aa22' },
    },
  },
  {
    id: 'header-male-40pin',
    name: 'Male Header Pins 40-Pin',
    category: 'prototyping',
    description: 'Forty-pin single-row male 2.54mm pitch header strip that can be cut to length.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'connector',
      size: [2.0, 0.2, 0.2],
      colors: { body: '#17171c', accent: '#cccccc', detail: '#888888' },
    },
  },
  {
    id: 'header-female-40pin',
    name: 'Female Header Pins 40-Pin',
    category: 'prototyping',
    description: 'Forty-pin single-row female 2.54mm pitch header socket for stacking or mating.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'connector',
      size: [2.0, 0.25, 0.2],
      colors: { body: '#17171c', accent: '#aaaaaa', detail: '#555555' },
    },
  },
  {
    id: 'dupont-jumper-wires',
    name: 'Dupont Jumper Wires M-M',
    category: 'prototyping',
    description: 'Set of male-to-male 20cm jumper wires for connecting breadboard components.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
    ],
    model: {
      kind: 'connector',
      size: [2.0, 0.08, 0.08],
      colors: { body: '#ff7759', accent: '#ffcc00', detail: '#1f6fb2' },
    },
  },
  {
    id: 'screw-terminal-4pin',
    name: '4-Pin Screw Terminal Block',
    category: 'prototyping',
    description: 'Four-position PCB-mount screw terminal for securely clamping multiple wires.',
    pins: [
      { name: 'A', role: 'signal' },
      { name: 'B', role: 'signal' },
      { name: 'C', role: 'signal' },
      { name: 'D', role: 'signal' },
    ],
    model: {
      kind: 'connector',
      size: [1.0, 0.3, 0.35],
      colors: { body: '#008800', accent: '#aaaaaa', detail: '#005500' },
    },
  },
  {
    id: 'proto-shield-uno',
    name: 'Prototype Shield for Uno',
    category: 'prototyping',
    description: 'Blank prototype shield that stacks onto Arduino Uno with a small onboard breadboard.',
    pins: [
      { name: '5V',  role: 'power'  },
      { name: 'GND', role: 'ground' },
      { name: 'D2',  role: 'digital'},
      { name: 'A0',  role: 'analog' },
    ],
    model: {
      kind: 'board',
      size: [2.0, 0.1, 1.7],
      colors: { body: '#228822', accent: '#aaffaa', detail: '#c8a200' },
    },
  },
  {
    id: 'pcb-blank-single',
    name: 'Single-Sided Blank PCB',
    category: 'prototyping',
    description: 'Blank single-sided copper-clad PCB board for etching custom circuit designs.',
    pins: [
      { name: 'PAD', role: 'signal' },
    ],
    model: {
      kind: 'breadboard',
      size: [2.0, 0.07, 1.5],
      colors: { body: '#228822', accent: '#c8a200', detail: '#116611' },
    },
  },
  {
    id: 'i2c-level-shifter',
    name: 'I2C Level Shifter',
    category: 'prototyping',
    description: 'Bidirectional logic level converter that bridges 3.3V and 5V I2C or SPI devices safely.',
    pins: [
      { name: 'HV',   role: 'power'  },
      { name: 'LV',   role: 'power'  },
      { name: 'GND',  role: 'ground' },
      { name: 'HV1',  role: 'signal' },
      { name: 'LV1',  role: 'signal' },
    ],
    model: {
      kind: 'module',
      size: [0.65, 0.08, 0.45],
      colors: { body: '#1f6fb2', accent: '#aaddff', detail: '#0d3349' },
    },
  },
];

export function listCategories() {
  return PART_CATEGORIES;
}

export function getPartsByCategory(categoryId) {
  if (categoryId === 'all') return PART_LIBRARY;
  return PART_LIBRARY.filter(p => p.category === categoryId);
}

export function searchParts(query) {
  if (!query || query.trim() === '') return PART_LIBRARY;
  const q = query.toLowerCase();
  return PART_LIBRARY.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}
